# Generated by Django 4.0.5 on 2022-06-25 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autor', '0003_remove_autor_apellidos_remove_autor_edad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='apellidos',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='autor',
            name='edad',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='autor',
            name='nacionalidad',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='autor',
            name='nombre',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
